# Generated by Django 5.2.7 on 2025-10-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "kpi_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("marketing", "Marketing"),
                            ("customer", "Customer"),
                            ("operations", "Operations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("current_value", models.CharField(max_length=100)),
                ("previous_value", models.CharField(blank=True, max_length=100)),
                (
                    "change_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "kpis",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="dashboard.kpi",
                    ),
                ),
            ],
            options={
                "db_table": "insights",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.FloatField()),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="dashboard.kpi",
                    ),
                ),
            ],
            options={
                "db_table": "metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["kpi", "-timestamp"], name="metrics_kpi_id_851e4b_idx"
                    )
                ],
            },
        ),
    ]
